apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf
  template:
    metadata:
      labels:
        app: bookshelf
    spec:
      containers:
        - name: bookshelf-server
          image: sashayakovtseva/bookshelf
          env:
            - name: MONGO_URL
              value: mongo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookshelf
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bookshelf
