apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: net-pod-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image-service
      name: net-pod
      namespace: default
    spec:
      containers:
      - name: image-server
        image: cloud.sylabs.io/sashayakovtseva/test/image-server
        imagePullPolicy: IfNotPresent
        command: ["./image-server"]
        workingDir: "/go/bin"
        ports:
        - containerPort: 8080
          hostPort: 80
