apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: default
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: mongo-pod
  template:
    metadata:
      labels:
        name: mongo-pod
    spec:
      containers:
        - name: mongo
          image: mongo:3.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: disk
          livenessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 27017
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: disk
          hostPath:
            type: DirectoryOrCreate
            path: /var/lib/mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
  selector:
    name: mongo-pod
  type: NodePort
