version: 2.0

defaults: &defaults
  working_directory: /go/src/github.com/sylabs/singularity-cri
  docker:
    - image: golang:1.11-stretch

jobs:
  get_source:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dep tool
          working_directory: /
          command: |
            mkdir -p $GOPATH/bin
            curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Ensure vendored dependencies
          command: |
            if [ ! -d vendor ]; then
              dep ensure -vendor-only
            fi
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/singularity-cri

  gometalinter_check:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /go
    - run:
        name: Install gometalinter
        working_directory: /
        command: curl -L https://git.io/vp6lP | sh
    - run:
        name: Check formatting
        command: make lint

  build_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Install libseccomp
          command: |
            apt-get update -y
            apt-get install -y libseccomp-dev
      - run:
          name: Build source
          command: make

  unit_test:
    machine: true
    steps:
      - attach_workspace:
          at: ~/go
      - run:
          name: Setup environment
          command: |
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export GOROOT=/usr/local/go' >> $BASH_ENV
            echo 'export GOCACHE=off' >> $BASH_ENV
            echo 'export PATH=$PATH:$GOPATH/bin:$GOROOT/bin' >> $BASH_ENV
            echo 'export PATH=$PATH:/usr/local/libexec/singularity/bin/' >> $BASH_ENV
      - run:
          name: Update go to 1.11
          working_directory: /tmp
          command: |
            wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.11.linux-amd64.tar.gz
      - run:
          name: Install dep tool
          command: |
            mkdir -p $GOPATH/bin
            curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Install dev libraries
          command: |
            sudo apt-get update -y
            sudo apt-get install -y build-essential libssl-dev uuid-dev squashfs-tools libseccomp-dev libgpgme11-dev
      - run:
          name: Singularity 3.0
          command: |
            git clone https://github.com/sylabs/singularity.git $GOPATH/src/github.com/sylabs/singularity
            cd $GOPATH/src/github.com/sylabs/singularity
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir
            sudo make -C ./builddir install
      - run:
          name: Run tests
          command: |
            cd $GOPATH/src/github.com/sylabs/singularity-cri
            make test
            cp cover.out $HOME
      - store_artifacts:
         path: ~/cover.out
         destination: cover_profile.out

workflows:
  version: 2
  build_and_test:
    jobs:
      - get_source
      - gometalinter_check:
          requires:
            - get_source
      - unit_test:
          requires:
            - get_source
      - build_source:
          requires:
            - get_source
