# unix socket to serve CRI requests on
# default: /var/run/singularity.sock
listenSocket: /var/run/singularity.sock

# directory to store all pulled images in
# default: /var/lib/singularity
storageDir: /var/lib/singularity

# address to serve streaming requests on (exec, attach, portforward)
# default: 127.0.0.1:12345
streamingURL: 127.0.0.1:12345

# directory to look for CNI plugin binaries
# default: /usr/local/libexec/singularity/cni
cniBinDir: /usr/local/libexec/singularity/cni

# directory to look for CNI network configuration files
# default: /usr/local/etc/singularity/network
cniConfDir: /usr/local/etc/singularity/network

# directory to store currently running pods and containers
# default: /var/run/singularity
baseRunDir: /var/run/singularity
