apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: net-pod-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image-service
      name: net-pod
      namespace: default
    spec:
      hostNetwork: true
      containers:
      - name: image-server
        image: cloud.sylabs.io/sashayakovtseva/test/image-server
        imagePullPolicy: Always
        command: ["./image-server"]
        workingDir: "/go/bin"
        ports:
        - containerPort: 8080
          hostPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: net-pod-service
  namespace: default
spec:
  selector:
    app: image-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  externalName: image-service
